[package]
name = "hive"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[[bin]]
name = "hive"
path = "src/main.rs"

[dependencies]
hive-domain.workspace = true
hive-application.workspace = true
hive-persistence.workspace = true
hive-api.workspace = true
tokio.workspace = true
uuid.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
