//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "administration_audit_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub actor_principal_id: Uuid,
    pub scope_type: super::enums::AdministrationScopeType,
    pub scope_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub action: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub reason: Option<String>,
    pub before_digest: Option<String>,
    pub after_digest: Option<String>,
    pub occurred_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary")]
    pub facts: Json,
    pub request_id: Option<Uuid>,
    pub correlation_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub graphql_operation: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_ip: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_agent: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::principals::Entity",
        from = "Column::ActorPrincipalId",
        to = "super::principals::Column::Id"
    )]
    Principals,
}

impl Related<super::principals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Principals.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
