//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "agent_operational_summaries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub agent_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub draft_validation_status: String,
    pub draft_error_count: i32,
    pub draft_warning_count: i32,
    pub draft_validated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub published_version: Option<String>,
    pub published_at: Option<DateTimeWithTimeZone>,
    pub alias_target_count: i32,
    pub active_alias_target_count: i32,
    #[sea_orm(column_type = "Text")]
    pub deployment_status: String,
    pub deployment_observed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub evaluation_outcome: String,
    pub evaluation_completed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub runtime_health: String,
    pub runtime_observed_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
