//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "agent_authoring_audit_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub agent_id: Uuid,
    pub project_id: Uuid,
    pub actor_principal_id: Uuid,
    pub action: super::enums::AgentAuthoringAuditAction,
    pub revision: Option<i64>,
    pub version_id: Option<Uuid>,
    pub content_digest: String,
    pub occurred_at: DateTimeWithTimeZone,
    pub request_id: Option<Uuid>,
    pub correlation_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub graphql_operation: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_ip: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_agent: Option<String>,
    pub organization_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::agents::Entity",
        from = "Column::AgentId",
        to = "super::agents::Column::Id"
    )]
    Agents,
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id"
    )]
    Projects,
    #[sea_orm(
        belongs_to = "super::principals::Entity",
        from = "Column::ActorPrincipalId",
        to = "super::principals::Column::Id"
    )]
    Principals,
    #[sea_orm(
        belongs_to = "super::agent_versions::Entity",
        from = "Column::VersionId",
        to = "super::agent_versions::Column::Id"
    )]
    AgentVersions,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id"
    )]
    Organizations,
}

impl Related<super::agents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Agents.def()
    }
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::principals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Principals.def()
    }
}

impl Related<super::agent_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentVersions.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
