//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "agents")]
pub struct Model {
    pub project_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub slug: String,
    #[sea_orm(column_type = "Text")]
    pub display_name: String,
    pub lifecycle_status: super::enums::AgentLifecycleStatus,
    // The primary key is declared last on purpose: Seaography applies `orderBy` columns in
    // declaration order, so a client that always adds the key gets it as the final tie-break.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id"
    )]
    Projects,
    #[sea_orm(has_many = "super::agent_authoring_audit_events::Entity")]
    AgentAuthoringAuditEvents,
    #[sea_orm(has_many = "super::agent_draft_audit_events::Entity")]
    AgentDraftAuditEvents,
    #[sea_orm(has_one = "super::agent_drafts::Entity")]
    AgentDrafts,
    #[sea_orm(has_one = "super::agent_operational_summaries::Entity")]
    AgentOperationalSummaries,
    #[sea_orm(has_one = "super::agent_operational_view_projection::Entity")]
    AgentOperationalViewProjection,
    #[sea_orm(has_many = "super::agent_versions::Entity")]
    AgentVersions,
    #[sea_orm(has_many = "super::deployments::Entity")]
    Deployments,
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::agent_authoring_audit_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentAuthoringAuditEvents.def()
    }
}

impl Related<super::agent_draft_audit_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentDraftAuditEvents.def()
    }
}

impl Related<super::agent_drafts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentDrafts.def()
    }
}

impl Related<super::agent_operational_summaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentOperationalSummaries.def()
    }
}

impl Related<super::agent_operational_view_projection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentOperationalViewProjection.def()
    }
}

impl Related<super::agent_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentVersions.def()
    }
}

impl Related<super::deployments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Deployments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::projects::Entity")]
    Projects,
    #[sea_orm(entity = "super::agent_versions::Entity")]
    AgentVersions,
    #[sea_orm(entity = "super::agent_operational_view_projection::Entity")]
    AgentOperationalViewProjection,
}
