//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "agent_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "agent_versions_agent_id_content_digest_key")]
    pub agent_id: Uuid,
    #[sea_orm(unique_key = "agent_versions_agent_id_version_number_key")]
    pub version_number: i64,
    #[sea_orm(column_type = "JsonBinary")]
    pub canonical_document: Json,
    #[sea_orm(unique_key = "agent_versions_agent_id_content_digest_key")]
    pub content_digest: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub dependency_versions: Json,
    #[sea_orm(column_type = "Text")]
    pub catalog_release_id: String,
    pub catalog_release_digest: String,
    pub published_by: Uuid,
    pub published_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::agents::Entity",
        from = "Column::AgentId",
        to = "super::agents::Column::Id"
    )]
    Agents,
}

impl Related<super::agents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Agents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::agents::Entity")]
    Agents,
}
