//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "catalog_definitions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub release_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub definition_kind: super::enums::CatalogDefinitionKind,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub identity: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub version: String,
    #[sea_orm(column_type = "Text")]
    pub display_name: String,
    pub content_digest: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub available_environments: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::catalog_releases::Entity",
        from = "Column::ReleaseId",
        to = "super::catalog_releases::Column::Id"
    )]
    CatalogReleases,
}

impl Related<super::catalog_releases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CatalogReleases.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
