//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "catalog_projection_heads")]
pub struct Model {
    #[sea_orm(column_type = "Text")]
    pub release_id: String,
    // The primary key is declared last on purpose: Seaography applies `orderBy` columns in
    // declaration order, so a client that always adds the key gets it as the final tie-break.
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::catalog_releases::Entity",
        from = "Column::ReleaseId",
        to = "super::catalog_releases::Column::Id"
    )]
    CatalogReleases,
}

impl Related<super::catalog_releases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CatalogReleases.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::catalog_releases::Entity")]
    CatalogReleases,
}
