//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "console_role_assignments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "console_role_assignments_principal_id_organization_id_proje_key")]
    pub principal_id: Uuid,
    #[sea_orm(unique_key = "console_role_assignments_principal_id_organization_id_proje_key")]
    pub organization_id: Option<Uuid>,
    #[sea_orm(unique_key = "console_role_assignments_principal_id_organization_id_proje_key")]
    pub project_id: Option<Uuid>,
    #[sea_orm(
        column_type = "Text",
        unique_key = "console_role_assignments_principal_id_organization_id_proje_key"
    )]
    pub role_code: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
