//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment_attempts")]
pub struct Model {
    #[sea_orm(unique_key = "deployment_attempts_deployment_id_attempt_number_key")]
    pub deployment_id: Uuid,
    pub deployment_plan_version_id: Uuid,
    #[sea_orm(unique_key = "deployment_attempts_deployment_id_attempt_number_key")]
    pub attempt_number: i64,
    pub status: super::enums::DeploymentAttemptStatus,
    pub generation: i64,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub completed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub failure_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub failure_summary: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    // The primary key is declared last on purpose: Seaography applies `orderBy` columns in
    // declaration order, so a client that always adds the key gets it as the final tie-break.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::deployments::Entity",
        from = "Column::DeploymentId",
        to = "super::deployments::Column::Id"
    )]
    Deployments,
    #[sea_orm(
        belongs_to = "super::deployment_plan_versions::Entity",
        from = "Column::DeploymentPlanVersionId",
        to = "super::deployment_plan_versions::Column::Id"
    )]
    DeploymentPlanVersions,
    #[sea_orm(has_many = "super::deployment_audit_events::Entity")]
    DeploymentAuditEvents,
    #[sea_orm(has_many = "super::deployment_stage_events::Entity")]
    DeploymentStageEvents,
}

impl Related<super::deployments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Deployments.def()
    }
}

impl Related<super::deployment_plan_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeploymentPlanVersions.def()
    }
}

impl Related<super::deployment_audit_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeploymentAuditEvents.def()
    }
}

impl Related<super::deployment_stage_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeploymentStageEvents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::deployments::Entity")]
    Deployments,
    #[sea_orm(entity = "super::deployment_plan_versions::Entity")]
    DeploymentPlanVersions,
    #[sea_orm(entity = "super::deployment_stage_events::Entity")]
    DeploymentStageEvents,
}
