//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment_approval_replay_receipts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub decision_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub request_id: Uuid,
    pub recorded_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::deployment_approval_decisions::Entity",
        from = "Column::DecisionId",
        to = "super::deployment_approval_decisions::Column::Id"
    )]
    DeploymentApprovalDecisions,
}

impl Related<super::deployment_approval_decisions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeploymentApprovalDecisions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
