//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment_approval_requirements")]
pub struct Model {
    #[sea_orm(unique)]
    pub deployment_id: Uuid,
    pub revision: i64,
    pub organization_id: Uuid,
    pub project_id: Uuid,
    pub requested_at: DateTimeWithTimeZone,
    pub required_approvers: i32,
    /// Withheld from the generated API: the stored value is the last state the maintenance tick
    /// wrote, and a requirement whose expiry has elapsed is reported `EXPIRED` before that tick
    /// runs. The computed `status` field answers that projection; the column cannot be selected,
    /// filtered or ordered on.
    #[seaography(ignore)]
    pub status: super::enums::ApprovalRequirementStatus,
    pub expires_at: DateTimeWithTimeZone,
    pub satisfied_at: Option<DateTimeWithTimeZone>,
    pub rejected_at: Option<DateTimeWithTimeZone>,
    pub invalidated_at: Option<DateTimeWithTimeZone>,
    pub invalidation_code: Option<super::enums::ApprovalInvalidationCode>,
    /// Withheld from the generated API: the stored `jsonb` array of principal identifiers is
    /// re-exposed as the computed `satisfiedParticipants` field, which answers the principal rows
    /// themselves.
    #[seaography(ignore)]
    #[sea_orm(column_type = "JsonBinary")]
    pub satisfied_participants: Json,
    pub created_at: DateTimeWithTimeZone,
    // The primary key is declared last on purpose: Seaography applies `orderBy` columns in
    // declaration order, so a client that always adds the key gets it as the final tie-break.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::deployments::Entity",
        from = "Column::DeploymentId",
        to = "super::deployments::Column::Id"
    )]
    Deployments,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id"
    )]
    Organizations,
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id"
    )]
    Projects,
    #[sea_orm(has_many = "super::deployment_approval_decisions::Entity")]
    DeploymentApprovalDecisions,
}

impl Related<super::deployments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Deployments.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::deployment_approval_decisions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeploymentApprovalDecisions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::deployments::Entity")]
    Deployments,
    #[sea_orm(entity = "super::organizations::Entity")]
    Organizations,
    #[sea_orm(entity = "super::projects::Entity")]
    Projects,
    #[sea_orm(entity = "super::deployment_approval_decisions::Entity")]
    DeploymentApprovalDecisions,
}
