//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment_plan_versions")]
pub struct Model {
    #[sea_orm(unique_key = "deployment_plan_versions_deployment_id_package_digest_key")]
    pub deployment_id: Uuid,
    #[sea_orm(unique_key = "deployment_plan_versions_deployment_id_version_number_key")]
    pub version_number: i64,
    pub agent_version_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub catalog_release_id: String,
    pub environment: super::enums::LogicalEnvironmentClass,
    #[sea_orm(column_type = "Text")]
    pub compiler_version: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub canonical_plan: Json,
    pub plan_digest: String,
    #[sea_orm(unique_key = "deployment_plan_versions_deployment_id_package_digest_key")]
    pub package_digest: String,
    #[sea_orm(column_type = "Text")]
    pub package_reference: String,
    pub created_by: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub environment_definition_version_id: Option<Uuid>,
    pub agent_content_digest: Option<String>,
    pub catalog_release_digest: Option<String>,
    pub target_digest: Option<String>,
    // The primary key is declared last on purpose: Seaography applies `orderBy` columns in
    // declaration order, so a client that always adds the key gets it as the final tie-break.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::deployments::Entity",
        from = "Column::DeploymentId",
        to = "super::deployments::Column::Id"
    )]
    Deployments,
    #[sea_orm(
        belongs_to = "super::agent_versions::Entity",
        from = "Column::AgentVersionId",
        to = "super::agent_versions::Column::Id"
    )]
    AgentVersions,
    #[sea_orm(
        belongs_to = "super::catalog_releases::Entity",
        from = "Column::CatalogReleaseId",
        to = "super::catalog_releases::Column::Id"
    )]
    CatalogReleases,
    #[sea_orm(
        belongs_to = "super::principals::Entity",
        from = "Column::CreatedBy",
        to = "super::principals::Column::Id"
    )]
    Principals,
    #[sea_orm(
        belongs_to = "super::environment_definition_versions::Entity",
        from = "Column::EnvironmentDefinitionVersionId",
        to = "super::environment_definition_versions::Column::Id"
    )]
    EnvironmentDefinitionVersions,
    #[sea_orm(has_many = "super::deployment_attempts::Entity")]
    DeploymentAttempts,
    #[sea_orm(has_one = "super::deployment_plan_review_facts::Entity")]
    DeploymentPlanReviewFacts,
}

impl Related<super::deployments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Deployments.def()
    }
}

impl Related<super::agent_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentVersions.def()
    }
}

impl Related<super::catalog_releases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CatalogReleases.def()
    }
}

impl Related<super::principals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Principals.def()
    }
}

impl Related<super::environment_definition_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EnvironmentDefinitionVersions.def()
    }
}

impl Related<super::deployment_attempts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeploymentAttempts.def()
    }
}

impl Related<super::deployment_plan_review_facts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeploymentPlanReviewFacts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::deployments::Entity")]
    Deployments,
    #[sea_orm(entity = "super::agent_versions::Entity")]
    AgentVersions,
    #[sea_orm(entity = "super::environment_definition_versions::Entity")]
    EnvironmentDefinitionVersions,
    #[sea_orm(entity = "super::deployment_plan_review_facts::Entity")]
    DeploymentPlanReviewFacts,
}
