//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment_approval_requirements")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub deployment_id: Uuid,
    pub revision: i64,
    pub organization_id: Uuid,
    pub project_id: Uuid,
    pub requested_at: DateTimeWithTimeZone,
    pub required_approvers: i32,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub expires_at: DateTimeWithTimeZone,
    pub satisfied_at: Option<DateTimeWithTimeZone>,
    pub rejected_at: Option<DateTimeWithTimeZone>,
    pub invalidated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub invalidation_code: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub satisfied_participants: Json,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
