//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment_stage_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "deployment_stage_events_deployment_attempt_id_sequence_numb_key")]
    pub deployment_attempt_id: Uuid,
    #[sea_orm(unique_key = "deployment_stage_events_deployment_attempt_id_sequence_numb_key")]
    pub sequence_number: i64,
    pub stage: super::enums::DeploymentStage,
    pub status: super::enums::DeploymentStageStatus,
    #[sea_orm(column_type = "Text")]
    pub message: String,
    pub occurred_at: DateTimeWithTimeZone,
    pub timeline_sequence: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::deployment_attempts::Entity",
        from = "Column::DeploymentAttemptId",
        to = "super::deployment_attempts::Column::Id"
    )]
    DeploymentAttempts,
}

impl Related<super::deployment_attempts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeploymentAttempts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
