//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub organization_id: Uuid,
    #[sea_orm(unique_key = "deployments_project_id_idempotency_key_key")]
    pub project_id: Uuid,
    pub agent_id: Uuid,
    pub agent_version_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub catalog_release_id: String,
    pub catalog_release_digest: String,
    #[sea_orm(column_type = "Text")]
    pub environment: String,
    pub target_digest: String,
    #[sea_orm(column_type = "Text")]
    pub strategy: String,
    #[sea_orm(column_type = "Text")]
    pub lifecycle_status: String,
    pub revision: i64,
    #[sea_orm(
        column_type = "Text",
        unique_key = "deployments_project_id_idempotency_key_key"
    )]
    pub idempotency_key: String,
    pub requested_by: Uuid,
    pub requested_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub environment_definition_version_id: Option<Uuid>,
    pub request_fingerprint: Option<String>,
    pub projection_revision: Option<i64>,
    pub project_lifecycle_revision: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
