//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment_policy_snapshots")]
pub struct Model {
    pub policy_id: Uuid,
    pub policy_revision: i64,
    pub policy_digest: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub policy_matrix: Json,
    pub logical_environment_class: super::enums::LogicalEnvironmentClass,
    pub risk: super::enums::DeploymentRisk,
    #[sea_orm(column_type = "JsonBinary")]
    pub required_evidence: Json,
    pub required_approvers: i32,
    pub created_at: DateTimeWithTimeZone,
    pub agent_version_id: Option<Uuid>,
    pub environment_definition_version_id: Option<Uuid>,
    pub target_digest: Option<String>,
    pub plan_digest: Option<String>,
    pub package_digest: Option<String>,
    pub binding_digest: Option<String>,
    pub evaluation_requirement_expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub risk_verification_digest: Option<String>,
    // The primary key is declared last on purpose: Seaography applies `orderBy` columns in
    // declaration order, so a client that always adds the key gets it as the final tie-break.
    #[sea_orm(primary_key, auto_increment = false)]
    pub deployment_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::deployments::Entity",
        from = "Column::DeploymentId",
        to = "super::deployments::Column::Id"
    )]
    Deployments,
    #[sea_orm(
        belongs_to = "super::project_approval_policies::Entity",
        from = "Column::PolicyId",
        to = "super::project_approval_policies::Column::Id"
    )]
    ProjectApprovalPolicies,
    #[sea_orm(
        belongs_to = "super::agent_versions::Entity",
        from = "Column::AgentVersionId",
        to = "super::agent_versions::Column::Id"
    )]
    AgentVersions,
    #[sea_orm(
        belongs_to = "super::environment_definition_versions::Entity",
        from = "Column::EnvironmentDefinitionVersionId",
        to = "super::environment_definition_versions::Column::Id"
    )]
    EnvironmentDefinitionVersions,
}

impl Related<super::deployments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Deployments.def()
    }
}

impl Related<super::project_approval_policies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectApprovalPolicies.def()
    }
}

impl Related<super::agent_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentVersions.def()
    }
}

impl Related<super::environment_definition_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EnvironmentDefinitionVersions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::deployments::Entity")]
    Deployments,
    #[sea_orm(entity = "super::project_approval_policies::Entity")]
    ProjectApprovalPolicies,
    #[sea_orm(entity = "super::agent_versions::Entity")]
    AgentVersions,
    #[sea_orm(entity = "super::environment_definition_versions::Entity")]
    EnvironmentDefinitionVersions,
}
