//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment_worker_heartbeats")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub worker_id: String,
    pub observed_at: DateTimeWithTimeZone,
    pub last_batch_deliveries: i32,
    pub pending_events: i32,
    pub oldest_pending_at: Option<DateTimeWithTimeZone>,
    pub state: super::enums::WorkerHeartbeatState,
    #[sea_orm(column_type = "Text", nullable)]
    pub failure_code: Option<String>,
    pub approval_execution_compatible: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
