//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment_evidence_snapshots")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "deployment_evidence_snapshots_deployment_id_evidence_kind_key")]
    pub deployment_id: Uuid,
    #[sea_orm(
        column_type = "Text",
        unique_key = "deployment_evidence_snapshots_deployment_id_evidence_kind_key"
    )]
    pub evidence_kind: String,
    pub evidence_digest: String,
    pub expires_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub agent_version_id: Option<Uuid>,
    pub environment_definition_version_id: Option<Uuid>,
    pub target_digest: Option<String>,
    pub plan_digest: Option<String>,
    pub package_digest: Option<String>,
    pub binding_digest: Option<String>,
    #[sea_orm(unique)]
    pub source_evaluation_run_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
