//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment_outbox_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub deployment_id: Uuid,
    pub event_type: super::enums::DeploymentOutboxEventType,
    #[sea_orm(column_type = "JsonBinary")]
    pub payload: Json,
    pub status: super::enums::DeploymentOutboxStatus,
    pub available_at: DateTimeWithTimeZone,
    pub claimed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub claimed_by: Option<String>,
    pub attempt_count: i32,
    pub delivered_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::deployments::Entity",
        from = "Column::DeploymentId",
        to = "super::deployments::Column::Id"
    )]
    Deployments,
    #[sea_orm(has_many = "super::deployment_outbox_delivery_audit_repairs::Entity")]
    DeploymentOutboxDeliveryAuditRepairs,
}

impl Related<super::deployments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Deployments.def()
    }
}

impl Related<super::deployment_outbox_delivery_audit_repairs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeploymentOutboxDeliveryAuditRepairs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
