//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment_plan_review_facts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub plan_id: Uuid,
    pub active_agent_version_number: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub change_summary: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub requested_dependency_versions: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub added_dependency_versions: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub removed_dependency_versions: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::deployment_plan_versions::Entity",
        from = "Column::PlanId",
        to = "super::deployment_plan_versions::Column::Id"
    )]
    DeploymentPlanVersions,
}

impl Related<super::deployment_plan_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeploymentPlanVersions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
