//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment_audit_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub deployment_id: Uuid,
    pub actor_principal_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub action: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub facts: Json,
    pub occurred_at: DateTimeWithTimeZone,
    pub deployment_attempt_id: Option<Uuid>,
    pub attempt_number: Option<i64>,
    pub timeline_sequence: Option<i64>,
    pub request_id: Option<Uuid>,
    pub correlation_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub graphql_operation: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_ip: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_agent: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
