//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment_evidence_snapshots")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "deployment_evidence_snapshots_deployment_id_evidence_kind_key")]
    pub deployment_id: Uuid,
    #[sea_orm(unique_key = "deployment_evidence_snapshots_deployment_id_evidence_kind_key")]
    pub evidence_kind: super::enums::DeploymentEvidenceKind,
    pub evidence_digest: String,
    pub expires_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub agent_version_id: Option<Uuid>,
    pub environment_definition_version_id: Option<Uuid>,
    pub target_digest: Option<String>,
    pub plan_digest: Option<String>,
    pub package_digest: Option<String>,
    pub binding_digest: Option<String>,
    #[sea_orm(unique)]
    pub source_evaluation_run_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::deployments::Entity",
        from = "Column::DeploymentId",
        to = "super::deployments::Column::Id"
    )]
    Deployments,
    #[sea_orm(
        belongs_to = "super::agent_versions::Entity",
        from = "Column::AgentVersionId",
        to = "super::agent_versions::Column::Id"
    )]
    AgentVersions,
    #[sea_orm(
        belongs_to = "super::environment_definition_versions::Entity",
        from = "Column::EnvironmentDefinitionVersionId",
        to = "super::environment_definition_versions::Column::Id"
    )]
    EnvironmentDefinitionVersions,
    #[sea_orm(
        belongs_to = "super::evaluation_runs::Entity",
        from = "Column::SourceEvaluationRunId",
        to = "super::evaluation_runs::Column::Id"
    )]
    EvaluationRuns,
    #[sea_orm(has_many = "super::deployment_evidence_invalidations::Entity")]
    DeploymentEvidenceInvalidations,
}

impl Related<super::deployments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Deployments.def()
    }
}

impl Related<super::agent_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentVersions.def()
    }
}

impl Related<super::environment_definition_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EnvironmentDefinitionVersions.def()
    }
}

impl Related<super::evaluation_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EvaluationRuns.def()
    }
}

impl Related<super::deployment_evidence_invalidations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeploymentEvidenceInvalidations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
