//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment_promotion_facts")]
pub struct Model {
    pub deployment_id: Uuid,
    #[sea_orm(unique)]
    pub action_receipt_id: Uuid,
    pub agent_version_id: Uuid,
    pub target_digest: String,
    pub runtime_health_generation: i64,
    pub occurred_at: DateTimeWithTimeZone,
    // The primary key is declared last on purpose: Seaography applies `orderBy` columns in
    // declaration order, so a client that always adds the key gets it as the final tie-break.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::deployments::Entity",
        from = "Column::DeploymentId",
        to = "super::deployments::Column::Id"
    )]
    Deployments,
    #[sea_orm(
        belongs_to = "super::deployment_recovery_action_receipts::Entity",
        from = "Column::ActionReceiptId",
        to = "super::deployment_recovery_action_receipts::Column::Id"
    )]
    DeploymentRecoveryActionReceipts,
    #[sea_orm(
        belongs_to = "super::agent_versions::Entity",
        from = "Column::AgentVersionId",
        to = "super::agent_versions::Column::Id"
    )]
    AgentVersions,
}

impl Related<super::deployments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Deployments.def()
    }
}

impl Related<super::deployment_recovery_action_receipts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeploymentRecoveryActionReceipts.def()
    }
}

impl Related<super::agent_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentVersions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::deployments::Entity")]
    Deployments,
    #[sea_orm(entity = "super::agent_versions::Entity")]
    AgentVersions,
}
