//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment_approval_decisions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "deployment_approval_decisions_approval_requirement_id_actor_key")]
    pub approval_requirement_id: Uuid,
    #[sea_orm(unique_key = "deployment_approval_decisions_approval_requirement_id_actor_key")]
    pub actor_principal_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub decision: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub comment: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub rejection_reason: Option<String>,
    pub eligibility_checked_at: DateTimeWithTimeZone,
    pub decided_at: DateTimeWithTimeZone,
    pub request_key: Option<Uuid>,
    pub correlation_id: Option<Uuid>,
    pub request_expected_revision: Option<i64>,
    pub request_fingerprint: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
