//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment_policy_snapshots")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub deployment_id: Uuid,
    pub policy_id: Uuid,
    pub policy_revision: i64,
    pub policy_digest: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub policy_matrix: Json,
    #[sea_orm(column_type = "Text")]
    pub logical_environment_class: String,
    #[sea_orm(column_type = "Text")]
    pub risk: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub required_evidence: Json,
    pub required_approvers: i32,
    pub created_at: DateTimeWithTimeZone,
    pub agent_version_id: Option<Uuid>,
    pub environment_definition_version_id: Option<Uuid>,
    pub target_digest: Option<String>,
    pub plan_digest: Option<String>,
    pub package_digest: Option<String>,
    pub binding_digest: Option<String>,
    pub evaluation_requirement_expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub risk_verification_digest: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
