//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment_plan_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "deployment_plan_versions_deployment_id_package_digest_key")]
    pub deployment_id: Uuid,
    #[sea_orm(unique_key = "deployment_plan_versions_deployment_id_version_number_key")]
    pub version_number: i64,
    pub agent_version_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub catalog_release_id: String,
    #[sea_orm(column_type = "Text")]
    pub environment: String,
    #[sea_orm(column_type = "Text")]
    pub compiler_version: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub canonical_plan: Json,
    pub plan_digest: String,
    #[sea_orm(unique_key = "deployment_plan_versions_deployment_id_package_digest_key")]
    pub package_digest: String,
    #[sea_orm(column_type = "Text")]
    pub package_reference: String,
    pub created_by: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub environment_definition_version_id: Option<Uuid>,
    pub agent_content_digest: Option<String>,
    pub catalog_release_digest: Option<String>,
    pub target_digest: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
