//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "environment_definition_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub catalog_release_id: String,
    pub catalog_release_digest: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "environment_definition_versio_stable_definition_id_content__key"
    )]
    pub stable_definition_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "environment_definition_version_stable_definition_id_version_key"
    )]
    pub version: String,
    #[sea_orm(column_type = "Text")]
    pub display_name: String,
    #[sea_orm(column_type = "Text")]
    pub logical_environment_class: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub canonical_document: Json,
    #[sea_orm(unique_key = "environment_definition_versio_stable_definition_id_content__key")]
    pub content_digest: String,
    pub published_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
