//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "environment_definition_versions")]
pub struct Model {
    #[sea_orm(column_type = "Text")]
    pub catalog_release_id: String,
    pub catalog_release_digest: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "environment_definition_versio_stable_definition_id_content__key"
    )]
    pub stable_definition_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "environment_definition_version_stable_definition_id_version_key"
    )]
    pub version: String,
    #[sea_orm(column_type = "Text")]
    pub display_name: String,
    pub logical_environment_class: super::enums::LogicalEnvironmentClass,
    #[sea_orm(column_type = "JsonBinary")]
    pub canonical_document: Json,
    #[sea_orm(unique_key = "environment_definition_versio_stable_definition_id_content__key")]
    pub content_digest: String,
    pub published_at: DateTimeWithTimeZone,
    // The primary key is declared last on purpose: Seaography applies `orderBy` columns in
    // declaration order, so a client that always adds the key gets it as the final tie-break.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::catalog_releases::Entity",
        from = "Column::CatalogReleaseId",
        to = "super::catalog_releases::Column::Id"
    )]
    CatalogReleases,
    #[sea_orm(has_many = "super::deployment_evidence_snapshots::Entity")]
    DeploymentEvidenceSnapshots,
    #[sea_orm(has_many = "super::deployment_plan_versions::Entity")]
    DeploymentPlanVersions,
    #[sea_orm(has_many = "super::deployment_policy_snapshots::Entity")]
    DeploymentPolicySnapshots,
    #[sea_orm(has_many = "super::deployments::Entity")]
    Deployments,
    #[sea_orm(has_many = "super::evaluation_runs::Entity")]
    EvaluationRuns,
    #[sea_orm(has_many = "super::evaluation_target_projections::Entity")]
    EvaluationTargetProjections,
    #[sea_orm(has_many = "super::evaluation_target_snapshots::Entity")]
    EvaluationTargetSnapshots,
}

impl Related<super::catalog_releases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CatalogReleases.def()
    }
}

impl Related<super::deployment_evidence_snapshots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeploymentEvidenceSnapshots.def()
    }
}

impl Related<super::deployment_plan_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeploymentPlanVersions.def()
    }
}

impl Related<super::deployment_policy_snapshots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeploymentPolicySnapshots.def()
    }
}

impl Related<super::deployments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Deployments.def()
    }
}

impl Related<super::evaluation_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EvaluationRuns.def()
    }
}

impl Related<super::evaluation_target_projections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EvaluationTargetProjections.def()
    }
}

impl Related<super::evaluation_target_snapshots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EvaluationTargetSnapshots.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::catalog_releases::Entity")]
    CatalogReleases,
    #[sea_orm(entity = "super::deployments::Entity")]
    Deployments,
    #[sea_orm(entity = "super::evaluation_target_projections::Entity")]
    EvaluationTargetProjections,
}
