//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "organization_membership_roles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub membership_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub role_code: super::enums::OrganizationRoleCode,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organization_memberships::Entity",
        from = "Column::MembershipId",
        to = "super::organization_memberships::Column::Id"
    )]
    OrganizationMemberships,
}

impl Related<super::organization_memberships::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationMemberships.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::organization_memberships::Entity")]
    OrganizationMemberships,
}
