//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "organization_memberships")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "organization_memberships_one_active")]
    pub organization_id: Uuid,
    #[sea_orm(unique_key = "organization_memberships_one_active")]
    pub principal_id: Uuid,
    pub started_at: DateTimeWithTimeZone,
    pub ended_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(unique_key = "organization_memberships_one_active")]
    pub active_marker: Option<bool>,
    pub revision: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id"
    )]
    Organizations,
    #[sea_orm(
        belongs_to = "super::principals::Entity",
        from = "Column::PrincipalId",
        to = "super::principals::Column::Id"
    )]
    Principals,
    #[sea_orm(has_many = "super::organization_membership_roles::Entity")]
    OrganizationMembershipRoles,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::principals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Principals.def()
    }
}

impl Related<super::organization_membership_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationMembershipRoles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
