//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "organizations")]
pub struct Model {
    #[sea_orm(column_type = "Text", unique)]
    pub slug: String,
    #[sea_orm(column_type = "Text")]
    pub display_name: String,
    pub lifecycle_status: super::enums::LifecycleStatus,
    pub revision: Option<i64>,
    // The primary key is declared last on purpose: Seaography applies `orderBy` columns in
    // declaration order, so a client that always adds the key gets it as the final tie-break.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::agent_authoring_audit_events::Entity")]
    AgentAuthoringAuditEvents,
    #[sea_orm(has_many = "super::agent_operational_view_projection::Entity")]
    AgentOperationalViewProjection,
    #[sea_orm(has_many = "super::audit_event_projection::Entity")]
    AuditEventProjection,
    #[sea_orm(has_many = "super::console_role_assignments::Entity")]
    ConsoleRoleAssignments,
    #[sea_orm(
        has_many = "super::deployment_approval_principal_organization_membership_scopes::Entity"
    )]
    DeploymentApprovalPrincipalOrganizationMembershipScopes,
    #[sea_orm(has_many = "super::deployment_approval_principal_organization_scopes::Entity")]
    DeploymentApprovalPrincipalOrganizationScopes,
    #[sea_orm(has_many = "super::deployment_approval_requirements::Entity")]
    DeploymentApprovalRequirements,
    #[sea_orm(has_many = "super::deployments::Entity")]
    Deployments,
    #[sea_orm(has_many = "super::organization_memberships::Entity")]
    OrganizationMemberships,
    #[sea_orm(has_many = "super::project_dashboard_projection::Entity")]
    ProjectDashboardProjection,
    #[sea_orm(has_many = "super::projects::Entity")]
    Projects,
}

impl Related<super::agent_authoring_audit_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentAuthoringAuditEvents.def()
    }
}

impl Related<super::agent_operational_view_projection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentOperationalViewProjection.def()
    }
}

impl Related<super::audit_event_projection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuditEventProjection.def()
    }
}

impl Related<super::console_role_assignments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConsoleRoleAssignments.def()
    }
}

impl Related<super::deployment_approval_principal_organization_membership_scopes::Entity>
    for Entity
{
    fn to() -> RelationDef {
        Relation::DeploymentApprovalPrincipalOrganizationMembershipScopes.def()
    }
}

impl Related<super::deployment_approval_principal_organization_scopes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeploymentApprovalPrincipalOrganizationScopes.def()
    }
}

impl Related<super::deployment_approval_requirements::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeploymentApprovalRequirements.def()
    }
}

impl Related<super::deployments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Deployments.def()
    }
}

impl Related<super::organization_memberships::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationMemberships.def()
    }
}

impl Related<super::project_dashboard_projection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectDashboardProjection.def()
    }
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::projects::Entity")]
    Projects,
    #[sea_orm(entity = "super::agent_operational_view_projection::Entity")]
    AgentOperationalViewProjection,
}
