//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "project_approval_policies")]
pub struct Model {
    #[sea_orm(unique)]
    pub project_id: Uuid,
    pub current_revision: i64,
    // The primary key is declared last on purpose: Seaography applies `orderBy` columns in
    // declaration order, so a client that always adds the key gets it as the final tie-break.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id"
    )]
    Projects,
    #[sea_orm(has_many = "super::deployment_policy_snapshots::Entity")]
    DeploymentPolicySnapshots,
    #[sea_orm(has_many = "super::project_approval_policy_versions::Entity")]
    ProjectApprovalPolicyVersions,
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::deployment_policy_snapshots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeploymentPolicySnapshots.def()
    }
}

impl Related<super::project_approval_policy_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectApprovalPolicyVersions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::projects::Entity")]
    Projects,
    #[sea_orm(entity = "super::project_approval_policy_versions::Entity")]
    ProjectApprovalPolicyVersions,
}
