//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "project_tool_connections")]
pub struct Model {
    #[sea_orm(unique_key = "project_tool_connections_server_id")]
    pub project_id: Uuid,
    #[sea_orm(
        column_type = "Text",
        unique_key = "project_tool_connections_project_id_name_key"
    )]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub definition_identity: String,
    #[sea_orm(column_type = "Text")]
    pub definition_version: String,
    pub environment: super::enums::LogicalEnvironmentClass,
    #[sea_orm(column_type = "Text")]
    pub redacted_secret_reference: String,
    pub lifecycle_status: super::enums::ConnectionLifecycleStatus,
    #[sea_orm(column_type = "Text")]
    pub rotation_summary: String,
    pub revision: i64,
    #[sea_orm(
        column_type = "Text",
        nullable,
        unique_key = "project_tool_connections_server_id"
    )]
    pub server_id: Option<String>,
    pub enabled: Option<bool>,
    #[sea_orm(column_type = "Text", nullable)]
    pub transport_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub stdio_command: Option<String>,
    // Not a generated field: a read exposes the computed `arguments`, which withholds stored
    // values that look like secret material.
    #[seaography(ignore)]
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub stdio_arguments: Option<Json>,
    // Not a generated field: a read exposes the computed `remoteUrl`, which withholds a stored
    // URL that carries credentials.
    #[seaography(ignore)]
    #[sea_orm(column_type = "Text", nullable)]
    pub remote_url: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub redacted_bindings: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub declared_tools: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub declared_resources: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub declared_prompts: Option<Json>,
    // The primary key is declared last on purpose: Seaography applies `orderBy` columns in
    // declaration order, so a client that always adds the key gets it as the final tie-break.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id"
    )]
    Projects,
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::projects::Entity")]
    Projects,
}
