//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "project_settings_connections")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "project_settings_connections_project_id_display_name_key")]
    pub project_id: Uuid,
    #[sea_orm(
        column_type = "Text",
        unique_key = "project_settings_connections_project_id_display_name_key"
    )]
    pub display_name: String,
    #[sea_orm(column_type = "Text")]
    pub definition_version: String,
    #[sea_orm(column_type = "Text")]
    pub environment: String,
    #[sea_orm(column_type = "Text")]
    pub credential_status: String,
    #[sea_orm(column_type = "Text")]
    pub lifecycle_status: String,
    pub revision: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
