//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "projects")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub organization_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub slug: String,
    #[sea_orm(column_type = "Text")]
    pub display_name: String,
    pub lifecycle_status: super::enums::LifecycleStatus,
    pub revision: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id"
    )]
    Organizations,
    #[sea_orm(has_many = "super::agents::Entity")]
    Agents,
    #[sea_orm(has_one = "super::project_dashboard_projection::Entity")]
    ProjectDashboardProjection,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::agents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Agents.def()
    }
}

impl Related<super::project_dashboard_projection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectDashboardProjection.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::organizations::Entity")]
    Organizations,
    #[sea_orm(entity = "super::agents::Entity")]
    Agents,
    #[sea_orm(entity = "super::project_dashboard_projection::Entity")]
    ProjectDashboardProjection,
}
