//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "project_settings_connections")]
pub struct Model {
    #[sea_orm(unique_key = "project_settings_connections_project_id_display_name_key")]
    pub project_id: Uuid,
    #[sea_orm(
        column_type = "Text",
        unique_key = "project_settings_connections_project_id_display_name_key"
    )]
    pub display_name: String,
    #[sea_orm(column_type = "Text")]
    pub definition_version: String,
    pub environment: super::enums::LogicalEnvironmentClass,
    pub credential_status: super::enums::CredentialStatus,
    pub lifecycle_status: super::enums::ConnectionLifecycleStatus,
    pub revision: i64,
    // The primary key is declared last on purpose: Seaography applies `orderBy` columns in
    // declaration order, so a client that always adds the key gets it as the final tie-break.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id"
    )]
    Projects,
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::projects::Entity")]
    Projects,
}
