//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "project_memberships")]
pub struct Model {
    #[sea_orm(unique_key = "project_memberships_one_active")]
    pub project_id: Uuid,
    #[sea_orm(unique_key = "project_memberships_one_active")]
    pub principal_id: Uuid,
    pub started_at: DateTimeWithTimeZone,
    pub ended_at: Option<DateTimeWithTimeZone>,
    pub revision: i64,
    #[sea_orm(unique_key = "project_memberships_one_active")]
    pub active_marker: Option<bool>,
    // The primary key is declared last on purpose: Seaography applies `orderBy` columns in
    // declaration order, so a client that always adds the key gets it as the final tie-break.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id"
    )]
    Projects,
    #[sea_orm(
        belongs_to = "super::principals::Entity",
        from = "Column::PrincipalId",
        to = "super::principals::Column::Id"
    )]
    Principals,
    #[sea_orm(has_many = "super::project_membership_roles::Entity")]
    ProjectMembershipRoles,
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::principals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Principals.def()
    }
}

impl Related<super::project_membership_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectMembershipRoles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::projects::Entity")]
    Projects,
    #[sea_orm(entity = "super::principals::Entity")]
    Principals,
    #[sea_orm(entity = "super::project_membership_roles::Entity")]
    ProjectMembershipRoles,
}
