//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "project_approval_policy_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub policy_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub revision: i64,
    pub digest: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub matrix: Json,
    #[sea_orm(column_type = "Text")]
    pub change_reason: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::project_approval_policies::Entity",
        from = "Column::PolicyId",
        to = "super::project_approval_policies::Column::Id"
    )]
    ProjectApprovalPolicies,
}

impl Related<super::project_approval_policies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectApprovalPolicies.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
