//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "reusable_resource_versions")]
pub struct Model {
    #[sea_orm(column_type = "JsonBinary")]
    pub canonical_document: Json,
    #[sea_orm(unique_key = "reusable_resource_versions_resource_id_content_digest_key")]
    pub content_digest: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub dependencies: Json,
    pub published_by: Uuid,
    pub published_at: DateTimeWithTimeZone,
    // The primary key is declared last on purpose: Seaography applies `orderBy` columns in
    // declaration order, so a client that always adds the key gets it as the final tie-break.
    #[sea_orm(
        primary_key,
        auto_increment = false,
        unique_key = "reusable_resource_versions_resource_id_content_digest_key"
    )]
    pub resource_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub version: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::reusable_resources::Entity",
        from = "Column::ResourceId",
        to = "super::reusable_resources::Column::Id"
    )]
    ReusableResources,
    #[sea_orm(
        belongs_to = "super::principals::Entity",
        from = "Column::PublishedBy",
        to = "super::principals::Column::Id"
    )]
    Principals,
}

impl Related<super::reusable_resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReusableResources.def()
    }
}

impl Related<super::principals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Principals.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::reusable_resources::Entity")]
    ReusableResources,
}
