//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "reusable_resource_versions")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        unique_key = "reusable_resource_versions_resource_id_content_digest_key"
    )]
    pub resource_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub version: i64,
    #[sea_orm(column_type = "JsonBinary")]
    pub canonical_document: Json,
    #[sea_orm(unique_key = "reusable_resource_versions_resource_id_content_digest_key")]
    pub content_digest: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub dependencies: Json,
    pub published_by: Uuid,
    pub published_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
