//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "reusable_resources")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "reusable_resources_project_kind_identity")]
    pub project_id: Uuid,
    #[sea_orm(unique_key = "reusable_resources_project_kind_identity")]
    pub resource_kind: super::enums::ReusableResourceKind,
    #[sea_orm(
        column_type = "Text",
        unique_key = "reusable_resources_project_id_resource_kind_name_key"
    )]
    pub name: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "reusable_resources_project_kind_identity"
    )]
    pub identity: String,
    pub current_draft_revision: i64,
    pub current_published_version: Option<i64>,
    pub lifecycle_status: super::enums::LifecycleStatus,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id"
    )]
    Projects,
    #[sea_orm(has_many = "super::reusable_resource_drafts::Entity")]
    ReusableResourceDrafts,
    #[sea_orm(has_many = "super::reusable_resource_versions::Entity")]
    ReusableResourceVersions,
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::reusable_resource_drafts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReusableResourceDrafts.def()
    }
}

impl Related<super::reusable_resource_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReusableResourceVersions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
