//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "reusable_resource_drafts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub resource_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub revision: i64,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub canonical_document: Json,
    pub content_digest: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub dependencies: Json,
    pub validation_status: super::enums::ReusableResourceValidationStatus,
    #[sea_orm(column_type = "JsonBinary")]
    pub diagnostics: Json,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::reusable_resources::Entity",
        from = "Column::ResourceId",
        to = "super::reusable_resources::Column::Id"
    )]
    ReusableResources,
}

impl Related<super::reusable_resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReusableResources.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
